version: '3.2'

services:

    gateway:
        build: ./gateway

    backend:
        build: ./backend
        volumes:
        - ./backend/src:/opt/src

    frontend:
        build: ./frontend
        volumes:
        - ./frontend/src:/opt/src
